## Projet_1 Exercice partie_1

In [1]:
import pandas as pd

## Etape 1 : Collecter des informations basiques sur chaque jeu de données

### Jeu des données (1)

In [3]:
df1 = pd.read_csv("data/EdStatsCountry-Series.csv")

In [4]:
df1.head(5)

,CountryCode,SeriesCode,DESCRIPTION,Unnamed: 3
0,ABW,SP.POP.TOTL,Data sources : United Nations World Population...,NaN
1,ABW,SP.POP.GROW,Data sources: United Nations World Population ...,NaN
2,AFG,SP.POP.GROW,Data sources: United Nations World Population ...,NaN
3,AFG,NY.GDP.PCAP.PP.CD,Estimates are based on regression.,NaN
4,AFG,SP.POP.TOTL,Data sources : United Nations World Population...,NaN

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 613 entries, 0 to 612
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CountryCode  613 non-null    object
 1   SeriesCode   613 non-null    object
 2   DESCRIPTION  613 non-null    object
 3   Unnamed: 3   0 non-null      float64
dtypes: float64(1), object(3)
memory usage: 19.3+ KB

#### Calculer le nombre de lignes et de colonnes.

In [6]:
df1.shape

(613, 4)

#### Calculer le nombre de doublons dans le jeu de données.

In [7]:
duplicates = {}
for col in df1.columns:
    duplicates[col]= int(df1[col].duplicated(keep= "first").sum())
print(duplicates)

{'CountryCode': 402, 'SeriesCode': 592, 'DESCRIPTION': 516, 'Unnamed: 3': 612}

#### Calculer la proportion de valeurs manquantes par colonne.

In [8]:
del df1["Unnamed: 3"]

In [9]:
for col in df1.columns:
    missing_vals = (df1[col].isnull().sum()/len(df1)) * 100
    print(f"{col} = {missing_vals:.1f} % de valeurs manquantes")

CountryCode = 0.0 % de valeurs manquantes
SeriesCode = 0.0 % de valeurs manquantes
DESCRIPTION = 0.0 % de valeurs manquantes

#### Calculer le nombre d'occurrences de chaque valeur possible de la colonne.

In [10]:
for col in df1.select_dtypes(include="object").columns:
    print(f"_________{col}________")
    print(df1[col].value_counts())
    print("\n")

_________CountryCode________
CountryCode
GEO    18
MDA    18
CYP    12
SRB    12
MUS    12
       ..
WSM     2
YEM     2
ZAF     2
ZMB     2
ZWE     2
Name: count, Length: 211, dtype: int64


_________SeriesCode________
SeriesCode
SP.POP.TOTL          211
SP.POP.GROW          211
NY.GDP.PCAP.PP.CD     19
NY.GNP.PCAP.PP.CD     19
NY.GDP.PCAP.PP.KD     19
NY.GNP.MKTP.PP.CD     14
NY.GDP.MKTP.PP.KD     14
NY.GDP.MKTP.PP.CD     14
SP.POP.1564.TO.ZS     13
SP.POP.TOTL.MA.ZS     13
SP.POP.TOTL.FE.ZS     13
SP.POP.0014.TO.ZS     13
NY.GNP.PCAP.CD         6
NY.GDP.PCAP.CD         5
NY.GDP.PCAP.KD         5
SP.POP.1564.MA.IN      4
SP.POP.0014.TO         4
SP.POP.1564.TO         4
SP.POP.1564.FE.IN      4
SP.POP.0014.MA.IN      4
SP.POP.0014.FE.IN      4
Name: count, dtype: int64


_________DESCRIPTION________
DESCRIPTION
Data sources : United Nations World Population Prospects                                              154
Data sources: United Nations World Population Prospects                                               137
Estimates are based on regression.                                                                     84
Data sources : Eurostat                                                                                54
Derived using ratio of age group from WPP and World Bank population.                                   24
                                                                                                     ...
Data sources : U.S. Census Bureau, United Nations Population and Vital Statistics Report                1
Data sources: General Statistics Office of Vietnam                                                      1
Data sources : General Statistics Office of Vietnam                                                     1
Data sources : World Bank's Kosovo coutnry office, Kosovo Agency of Statistics, U.S. Census Bureau      1
Data sources: World Bank's Kosovo coutnry office, Kosovo Agency of Statistics, U.S. Census Bureau       1
Name: count, Length: 97, dtype: int64

### Jeu des données (2)

In [11]:
df2 = pd.read_csv("data/EdStatsCountry.csv")

In [12]:
df2.head()

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,Unnamed: 31
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,SNA data for 2000-2011 are updated from offici...,Latin America & Caribbean,High income: nonOECD,AW,...,NaN,2010,NaN,NaN,Yes,NaN,NaN,2012.0,NaN,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,General Data Dissemination System (GDDS),1979,"Multiple Indicator Cluster Survey (MICS), 2010/11","Integrated household survey (IHS), 2008",NaN,2013/14,NaN,2012.0,2000,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,"April 2013 database update: Based on IMF data,...",Sub-Saharan Africa,Upper middle income,AO,...,General Data Dissemination System (GDDS),1970,"Malaria Indicator Survey (MIS), 2011","Integrated household survey (IHS), 2008",NaN,2015,NaN,NaN,2005,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,General Data Dissemination System (GDDS),2011,"Demographic and Health Survey (DHS), 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2010.0,2012.0,2006,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income: nonOECD,AD,...,NaN,2011. Population figures compiled from adminis...,NaN,NaN,Yes,NaN,NaN,2006.0,NaN,NaN

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 32 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country Code                                       241 non-null    object
 1   Short Name                                         241 non-null    object
 2   Table Name                                         241 non-null    object
 3   Long Name                                          241 non-null    object
 4   2-alpha code                                       238 non-null    object
 5   Currency Unit                                      215 non-null    object
 6   Special Notes                                      145 non-null    object
 7   Region                                             214 non-null    object
 8   Income Group                                       214 non-null    object
 9   WB-2 code                                          240 non-null    object
 10  National accounts base year                        205 non-null    object
 11  National accounts reference year                   32 non-null     float64
 12  SNA price valuation                                197 non-null    object
 13  Lending category                                   144 non-null    object
 14  Other groups                                       58 non-null     object
 15  System of National Accounts                        215 non-null    object
 16  Alternative conversion factor                      47 non-null     object
 17  PPP survey year                                    145 non-null    object
 18  Balance of Payments Manual in use                  181 non-null    object
 19  External debt Reporting status                     124 non-null    object
 20  System of trade                                    200 non-null    object
 21  Government Accounting concept                      161 non-null    object
 22  IMF data dissemination standard                    181 non-null    object
 23  Latest population census                           213 non-null    object
 24  Latest household survey                            141 non-null    object
 25  Source of most recent Income and expenditure data  160 non-null    object
 26  Vital registration complete                        111 non-null    object
 27  Latest agricultural census                         142 non-null    object
 28  Latest industrial data                             107 non-null    float64
 29  Latest trade data                                  185 non-null    float64
 30  Latest water withdrawal data                       179 non-null    object
 31  Unnamed: 31                                        0 non-null      float64
dtypes: float64(4), object(28)
memory usage: 60.4+ KB

#### Calculer le nombre de lignes et de colonnes.

In [14]:
df2.shape

(241, 32)

#### Calculer le nombre de doublons dans le jeu de données.

In [15]:
print(df2.duplicated().sum())

0

#### Calculer la proportion de valeurs manquantes par colonne.

In [16]:
del df2["Unnamed: 31"]
round((df2.isnull().sum()/len(df2))* 100,2)

Country Code                                          0.00
Short Name                                            0.00
Table Name                                            0.00
Long Name                                             0.00
2-alpha code                                          1.24
Currency Unit                                        10.79
Special Notes                                        39.83
Region                                               11.20
Income Group                                         11.20
WB-2 code                                             0.41
National accounts base year                          14.94
National accounts reference year                     86.72
SNA price valuation                                  18.26
Lending category                                     40.25
Other groups                                         75.93
System of National Accounts                          10.79
Alternative conversion factor                        80.50
PPP survey year                                      39.83
Balance of Payments Manual in use                    24.90
External debt Reporting status                       48.55
System of trade                                      17.01
Government Accounting concept                        33.20
IMF data dissemination standard                      24.90
Latest population census                             11.62
Latest household survey                              41.49
Source of most recent Income and expenditure data    33.61
Vital registration complete                          53.94
Latest agricultural census                           41.08
Latest industrial data                               55.60
Latest trade data                                    23.24
Latest water withdrawal data                         25.73
dtype: float64

#### Calculer les statistiques descriptives

In [17]:
df2.describe(include = "number")

,National accounts reference year,Latest industrial data,Latest trade data
count,32.00000,107.000000,185.000000
mean,2001.53125,2008.102804,2010.994595
std,5.24856,2.616834,2.569675
min,1987.00000,2000.000000,1995.000000
25%,1996.75000,2007.500000,2011.000000
50%,2002.00000,2009.000000,2012.000000
75%,2005.00000,2010.000000,2012.000000
max,2012.00000,2010.000000,2012.000000

#### Calculer le nombre d'occurrences (Colonnes catégorielles)

In [18]:
for col in df2.select_dtypes(include = "object").columns:
    print(f"_________{col}_________")
    print(df2[col].value_counts())
    print("\n")

_________Country Code_________
Country Code
ABW    1
AFG    1
AGO    1
ALB    1
AND    1
      ..
XKX    1
YEM    1
ZAF    1
ZMB    1
ZWE    1
Name: count, Length: 241, dtype: int64


_________Short Name_________
Short Name
Aruba           1
Afghanistan     1
Angola          1
Albania         1
Andorra         1
               ..
Kosovo          1
Yemen           1
South Africa    1
Zambia          1
Zimbabwe        1
Name: count, Length: 241, dtype: int64


_________Table Name_________
Table Name
Aruba           1
Afghanistan     1
Angola          1
Albania         1
Andorra         1
               ..
Kosovo          1
Yemen, Rep.     1
South Africa    1
Zambia          1
Zimbabwe        1
Name: count, Length: 241, dtype: int64


_________Long Name_________
Long Name
Aruba                           1
Islamic State of Afghanistan    1
People's Republic of Angola     1
Republic of Albania             1
Principality of Andorra         1
                               ..
Republic of Kosovo              1
Republic of Yemen               1
Republic of South Africa        1
Republic of Zambia              1
Republic of Zimbabwe            1
Name: count, Length: 241, dtype: int64


_________2-alpha code_________
2-alpha code
AW    1
AF    1
AO    1
AL    1
AD    1
     ..
WS    1
YE    1
ZA    1
ZM    1
ZW    1
Name: count, Length: 238, dtype: int64


_________Currency Unit_________
Currency Unit
Euro                     23
U.S. dollar              14
CFA franc                14
East Caribbean dollar     6
Australian dollar         3
                         ..
Vanuatu vatu              1
Samoan tala               1
Yemeni rial               1
South African rand        1
New Zambian kwacha        1
Name: count, Length: 152, dtype: int64


_________Special Notes_________
Special Notes
April 2012 database update: Based on official government statistics, national accounts data were revised for 2000 onward; the base year changed to 2006.                                                                                              6
Fiscal year end: March 31; reporting period for national accounts data: CY.                                                                                                                                                                           4
Fiscal year end: June 30; reporting period for national accounts data: CY.                                                                                                                                                                            3
April 2013 database update: Based on IMF data, national accounts data were revised for 2000 onward; the base year changed to 2000.                                                                                                                    2
Fiscal year end: March 31; reporting period for national accounts data: FY.                                                                                                                                                                           2
                                                                                                                                                                                                                                                     ..
Fiscal year ends on June 30; reporting period for national accounts data: FY. Data are revised from Samoa Bureau of Statistics and Central Bank of Samoa.                                                                                             1
Kosovo became a World Bank member on June 29, 2009. Since 1999, Kosovo has been a territory under international administration pursuant to UN Security Council Resolution 1244 (1999).                                                                1
Based on official government statistics and International Monetary Fund data, national accounts data have been revised for 1990 onward.                                                                                                               1
National accounts data have rebased to reflect the January 1, 2013, introduction of the new Zambian kwacha at a rate of 1,000 old kwacha = 1 new kwacha.                                                                                              1
Fiscal year end: June 30; reporting period for national accounts data: CY. As of January 2009, multiple hard currencies, such as rand, pound sterling, euro and U.S. dollar are in use. Data are reported in U.S. dollars, the most-used currency.    1
Name: count, Length: 131, dtype: int64


_________Region_________
Region
Europe & Central Asia         57
Sub-Saharan Africa            48
Latin America & Caribbean     41
East Asia & Pacific           36
Middle East & North Africa    21
South Asia                     8
North America                  3
Name: count, dtype: int64


_________Income Group_________
Income Group
Upper middle income     55
Lower middle income     50
High income: nonOECD    44
Low income              34
High income: OECD       31
Name: count, dtype: int64


_________WB-2 code_________
WB-2 code
AW    1
AF    1
AO    1
AL    1
AD    1
     ..
KV    1
RY    1
ZA    1
ZM    1
ZW    1
Name: count, Length: 240, dtype: int64


_________National accounts base year_________
National accounts base year
2005                                                                                                                       34
Original chained constant price data are rescaled.                                                                         28
2000                                                                                                                       25
2006                                                                                                                       19
1990                                                                                                                       11
2007                                                                                                                        9
2004                                                                                                                        8
2010                                                                                                                        6
2003                                                                                                                        5
1999                                                                                                                        4
2002                                                                                                                        4
2009                                                                                                                        3
1985                                                                                                                        3
1991                                                                                                                        3
2008                                                                                                                        3
1994                                                                                                                        3
1988                                                                                                                        3
2001                                                                                                                        3
1998                                                                                                                        3
2011                                                                                                                        2
1997                                                                                                                        2
1995                                                                                                                        2
2005/06                                                                                                                     2
2002/03                                                                                                                     1
1991/92                                                                                                                     1
1996                                                                                                                        1
1980                                                                                                                        1
1997/98                                                                                                                     1
2004/05                                                                                                                     1
1986/87                                                                                                                     1
1974                                                                                                                        1
1995/96                                                                                                                     1
2012                                                                                                                        1
1987                                                                                                                        1
1984                                                                                                                        1
2000/01                                                                                                                     1
2005/2006                                                                                                                   1
1954                                                                                                                        1
1990/91                                                                                                                     1
1981/82. Reporting period switch from fiscal year to calendar year from 1996. Pre-1996 data converted to calendar year.     1
2010/11                                                                                                                     1
2001/02                                                                                                                     1
1982                                                                                                                        1
Name: count, dtype: int64


_________SNA price valuation_________
SNA price valuation
Value added at basic prices (VAB)       163
Value added at producer prices (VAP)     34
Name: count, dtype: int64


_________Lending category_________
Lending category
IBRD     67
IDA      59
Blend    18
Name: count, dtype: int64


_________Other groups_________
Other groups
HIPC         40
Euro area    18
Name: count, dtype: int64


_________System of National Accounts_________
System of National Accounts
Country uses the 1993 System of National Accounts methodology.    165
Country uses the 1968 System of National Accounts methodology.     42
Country uses the 2008 System of National Accounts methodology.      8
Name: count, dtype: int64


_________Alternative conversion factor_________
Alternative conversion factor
1990–95               8
1987–95               5
1993                  3
1992–95               2
1991                  2
1992                  1
1971–84               1
1992–93               1
1960–85               1
1978–89, 1991–92      1
1999–2001             1
1978–93               1
1992–94               1
1973–87               1
1965–84               1
1991–96               1
1988–89               1
1980–2002             1
1997, 2004            1
1986                  1
1971–98               1
1965–95               1
1985–90               1
1989                  1
1987–89, 1992         1
1994                  1
1977–90               1
1970–2010             1
1987–95, 1997–2007    1
1990–96               1
1990–92               1
1991, 1998            1
Name: count, dtype: int64


_________PPP survey year_________
PPP survey year
2005       98
Rolling    37
2011       10
Name: count, dtype: int64


_________Balance of Payments Manual in use_________
Balance of Payments Manual in use
IMF Balance of Payments Manual, 6th edition.    181
Name: count, dtype: int64


_________External debt Reporting status_________
External debt Reporting status
Actual         107
Estimate        11
Preliminary      6
Name: count, dtype: int64


_________System of trade_________
System of trade
General trade system    106
Special trade system     94
Name: count, dtype: int64


_________Government Accounting concept_________
Government Accounting concept
Consolidated central government    95
Budgetary central government       66
Name: count, dtype: int64


_________IMF data dissemination standard_________
IMF data dissemination standard
General Data Dissemination System (GDDS)      110
Special Data Dissemination Standard (SDDS)     71
Name: count, dtype: int64


_________Latest population census_________
Latest population census
2011                                                                                                                                                                              59
2010                                                                                                                                                                              49
2012                                                                                                                                                                              18
2009                                                                                                                                                                              14
2008                                                                                                                                                                               9
2007                                                                                                                                                                               9
2006                                                                                                                                                                               8
2013                                                                                                                                                                               8
2004                                                                                                                                                                               7
2002                                                                                                                                                                               5
2005                                                                                                                                                                               4
2011. Population figures compiled from administrative registers.                                                                                                                   3
2003                                                                                                                                                                               3
1984                                                                                                                                                                               2
1970                                                                                                                                                                               2
1998                                                                                                                                                                               2
1979                                                                                                                                                                               1
2006. Rolling census based on continuous sample survey.                                                                                                                            1
Guernsey: 2009; Jersey: 2011.                                                                                                                                                      1
1996                                                                                                                                                                               1
2011. The population censuses for 1986 and 1996 were based on a one-in-seven sample of the population, while that for 2006 was based on a one-in-ten sample of the population.     1
1997                                                                                                                                                                               1
1993                                                                                                                                                                               1
1983                                                                                                                                                                               1
1987                                                                                                                                                                               1
2001                                                                                                                                                                               1
1989                                                                                                                                                                               1
Name: count, dtype: int64


_________Latest household survey_________
Latest household survey
Multiple Indicator Cluster Survey (MICS), 2012                                                                                                   10
World Health Survey (WHS), 2003                                                                                                                  10
Demographic and Health Survey (DHS), 2013                                                                                                        10
Multiple Indicator Cluster Survey (MICS), 2011                                                                                                    9
Multiple Indicator Cluster Survey (MICS), 2010                                                                                                    9
Demographic and Health Survey (DHS), 2012                                                                                                         8
Demographic and Health Survey (DHS), 2011                                                                                                         6
Demographic and Health Survey (DHS), 2009                                                                                                         4
Demographic and Health Survey (DHS), 2011/12                                                                                                      4
Demographic and Health Survey (DHS), 2010                                                                                                         4
Multiple Indicator Cluster Survey (MICS), 2011/12                                                                                                 4

### Jeu des données (3)

In [19]:
df3 = pd.read_csv("data/EdStatsData.csv")
df3.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1970,1971,1972,1973,1974,1975,...,2060,2065,2070,2075,2080,2085,2090,2095,2100,Unnamed: 69
0,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.F,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.GPI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,"Adjusted net enrolment rate, lower secondary, ...",UIS.NERA.2.M,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,"Adjusted net enrolment rate, primary, both sex...",SE.PRM.TENR,54.822121,54.894138,56.209438,57.267109,57.991138,59.36554,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 886930 entries, 0 to 886929
Data columns (total 70 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Country Name    886930 non-null  object
 1   Country Code    886930 non-null  object
 2   Indicator Name  886930 non-null  object
 3   Indicator Code  886930 non-null  object
 4   1970            72288 non-null   float64
 5   1971            35537 non-null   float64
 6   1972            35619 non-null   float64
 7   1973            35545 non-null   float64
 8   1974            35730 non-null   float64
 9   1975            87306 non-null   float64
 10  1976            37483 non-null   float64
 11  1977            37574 non-null   float64
 12  1978            37576 non-null   float64
 13  1979            36809 non-null   float64
 14  1980            89122 non-null   float64
 15  1981            38777 non-null   float64
 16  1982            37511 non-null   float64
 17  1983            38460 non-null   float64
 18  1984            38606 non-null   float64
 19  1985            90296 non-null   float64
 20  1986            39372 non-null   float64
 21  1987            38641 non-null   float64
 22  1988            38552 non-null   float64
 23  1989            37540 non-null   float64
 24  1990            124405 non-null  float64
 25  1991            74437 non-null   float64
 26  1992            75543 non-null   float64
 27  1993            75793 non-null   float64
 28  1994            77462 non-null   float64
 29  1995            131361 non-null  float64
 30  1996            76807 non-null   float64
 31  1997            73453 non-null   float64
 32  1998            84914 non-null   float64
 33  1999            118839 non-null  float64
 34  2000            176676 non-null  float64
 35  2001            123509 non-null  float64
 36  2002            124205 non-null  float64
 37  2003            130363 non-null  float64
 38  2004            128814 non-null  float64
 39  2005            184108 non-null  float64
 40  2006            140312 non-null  float64
 41  2007            137272 non-null  float64
 42  2008            134387 non-null  float64
 43  2009            142108 non-null  float64
 44  2010            242442 non-null  float64
 45  2011            146012 non-null  float64
 46  2012            147264 non-null  float64
 47  2013            137509 non-null  float64
 48  2014            113789 non-null  float64
 49  2015            131058 non-null  float64
 50  2016            16460 non-null   float64
 51  2017            143 non-null     float64
 52  2020            51436 non-null   float64
 53  2025            51436 non-null   float64
 54  2030            51436 non-null   float64
 55  2035            51436 non-null   float64
 56  2040            51436 non-null   float64
 57  2045            51436 non-null   float64
 58  2050            51436 non-null   float64
 59  2055            51436 non-null   float64
 60  2060            51436 non-null   float64
 61  2065            51436 non-null   float64
 62  2070            51436 non-null   float64
 63  2075            51436 non-null   float64
 64  2080            51436 non-null   float64
 65  2085            51436 non-null   float64
 66  2090            51436 non-null   float64
 67  2095            51436 non-null   float64
 68  2100            51436 non-null   float64
 69  Unnamed: 69     0 non-null       float64
dtypes: float64(66), object(4)
memory usage: 473.7+ MB

#### Calculer le nombre de lignes et de colonnes.

In [21]:
df3.shape

(886930, 70)

#### Calculer le nombre de doublons dans le jeu de données.

In [22]:
del df3["Unnamed: 69"]
print(df3.duplicated().sum())

0

#### Calculer la proportion de valeurs manquantes par colonne.

In [23]:
round((df3.isnull().sum()/len(df3))* 100,2)

Country Name       0.00
Country Code       0.00
Indicator Name     0.00
Indicator Code     0.00
1970              91.85
                  ...
2080              94.20
2085              94.20
2090              94.20
2095              94.20
2100              94.20
Length: 69, dtype: float64

#### Calculer les statistiques descriptives

In [24]:
df3.describe(include="number")

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2055,2060,2065,2070,2075,2080,2085,2090,2095,2100
count,7.228800e+04,3.553700e+04,3.561900e+04,3.554500e+04,3.573000e+04,8.730600e+04,3.748300e+04,3.757400e+04,3.757600e+04,3.680900e+04,...,5.143600e+04,5.143600e+04,5.143600e+04,5.143600e+04,5.143600e+04,5.143600e+04,5.143600e+04,5.143600e+04,5.143600e+04,5.143600e+04
mean,1.974772e+09,4.253638e+09,4.592365e+09,5.105006e+09,5.401493e+09,2.314288e+09,5.731808e+09,6.124437e+09,6.671489e+09,7.436724e+09,...,7.145788e+02,7.224868e+02,7.271290e+02,7.283779e+02,7.266484e+02,7.228327e+02,7.176899e+02,7.113072e+02,7.034274e+02,6.940296e+02
std,1.211687e+11,1.804814e+11,1.914083e+11,2.059170e+11,2.112150e+11,1.375059e+11,2.215546e+11,2.325489e+11,2.473986e+11,2.660957e+11,...,2.136851e+04,2.215845e+04,2.287990e+04,2.352338e+04,2.408149e+04,2.455897e+04,2.496587e+04,2.530183e+04,2.556069e+04,2.574189e+04
min,-1.435564e+00,-1.594625e+00,-3.056522e+00,-4.032582e+00,-4.213563e+00,-3.658569e+00,-2.950945e+00,-3.174870e+00,-3.558749e+00,-2.973612e+00,...,-1.830000e+00,-1.630000e+00,-1.440000e+00,-1.260000e+00,-1.090000e+00,-9.200000e-01,-7.800000e-01,-6.500000e-01,-5.500000e-01,-4.500000e-01
25%,8.900000e-01,8.853210e+00,9.240920e+00,9.595200e+00,9.861595e+00,1.400000e+00,9.312615e+00,9.519913e+00,1.000000e+01,1.000000e+01,...,3.000000e-02,3.000000e-02,3.000000e-02,2.000000e-02,2.000000e-02,1.000000e-02,1.000000e-02,1.000000e-02,1.000000e-02,1.000000e-02
50%,6.317724e+00,6.316240e+01,6.655139e+01,6.969595e+01,7.087760e+01,9.677420e+00,7.101590e+01,7.133326e+01,7.290512e+01,7.510173e+01,...,2.300000e-01,2.300000e-01,2.300000e-01,2.300000e-01,2.300000e-01,2.300000e-01,2.300000e-01,2.300000e-01,2.300000e-01,2.200000e-01
75%,6.251250e+01,5.655200e+04,5.863650e+04,6.202900e+04,6.383675e+04,7.854163e+01,5.682800e+04,5.739175e+04,5.940425e+04,6.411500e+04,...,7.500000e+00,7.505000e+00,7.500000e+00,7.300000e+00,7.100000e+00,6.722500e+00,6.080000e+00,5.462500e+00,4.680000e+00,4.032500e+00
max,1.903929e+13,1.986457e+13,2.100916e+13,2.238367e+13,2.282991e+13,2.300634e+13,2.424128e+13,2.521383e+13,2.622101e+13,2.730873e+13,...,2.813670e+06,2.951569e+06,3.070879e+06,3.169711e+06,3.246239e+06,3.301586e+06,3.337871e+06,3.354746e+06,3.351887e+06,3.330484e+06

#### Calculer le nombre d'occurrences (Colonnes catégorielles)

In [25]:
for col in df3.select_dtypes(include="object").columns:
    print(f"__________{col}_________")
    print(df3[col].value_counts())
    print("\n")

__________Country Name_________
Country Name
Arab World                                     3665
East Asia & Pacific                            3665
East Asia & Pacific (excluding high income)    3665
Euro area                                      3665
Europe & Central Asia                          3665
                                               ...
Virgin Islands (U.S.)                          3665
West Bank and Gaza                             3665
Yemen, Rep.                                    3665
Zambia                                         3665
Zimbabwe                                       3665
Name: count, Length: 242, dtype: int64


__________Country Code_________
Country Code
ARB    3665
EAS    3665
EAP    3665
EMU    3665
ECS    3665
       ...
VIR    3665
PSE    3665
YEM    3665
ZMB    3665
ZWE    3665
Name: count, Length: 242, dtype: int64


__________Indicator Name_________
Indicator Name
Youth literacy rate, population 15-24 years, male (%)                                                  242
Adjusted net enrolment rate, lower secondary, both sexes (%)                                           242
Adjusted net enrolment rate, lower secondary, female (%)                                               242
Adjusted net enrolment rate, lower secondary, gender parity index (GPI)                                242
Adjusted net enrolment rate, lower secondary, male (%)                                                 242
                                                                                                      ...
Adult literacy rate, population 15+ years, both sexes (%)                                              242
Adult literacy rate, population 15+ years, female (%)                                                  242
Adult literacy rate, population 15+ years, gender parity index (GPI)                                   242
Adult literacy rate, population 15+ years, male (%)                                                    242
Africa Dataset: Average number of grades per multigrade class in primary schools (number of grades)    242
Name: count, Length: 3665, dtype: int64


__________Indicator Code_________
Indicator Code
SE.ADT.1524.LT.MA.ZS    242
UIS.NERA.2              242
UIS.NERA.2.F            242
UIS.NERA.2.GPI          242
UIS.NERA.2.M            242
                       ...
SE.ADT.LITR.ZS          242
SE.ADT.LITR.FE.ZS       242
UIS.LR.AG15T99.GPI      242
SE.ADT.LITR.MA.ZS       242
UIS.AFR.AGRADMG.1.PU    242
Name: count, Length: 3665, dtype: int64

### Jeu des données (4)

In [26]:
df4 = pd.read_csv("data/EdStatsFootNote.csv")

In [27]:
df4.head()

  CountryCode      SeriesCode    Year          DESCRIPTION  Unnamed: 4
0         ABW  SE.PRE.ENRL.FE  YR2001  Country estimation.         NaN
1         ABW  SE.TER.TCHR.FE  YR2005  Country estimation.         NaN
2         ABW  SE.PRE.TCHR.FE  YR2000  Country estimation.         NaN
3         ABW  SE.SEC.ENRL.GC  YR2004  Country estimation.         NaN
4         ABW     SE.PRE.TCHR  YR2006  Country estimation.         NaN

In [28]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 643638 entries, 0 to 643637
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   CountryCode  643638 non-null  object
 1   SeriesCode   643638 non-null  object
 2   Year         643638 non-null  object
 3   DESCRIPTION  643638 non-null  object
 4   Unnamed: 4   0 non-null       float64
dtypes: float64(1), object(4)
memory usage: 24.6+ MB

#### Calculer le nombre de lignes et de colonnes.

In [29]:
df4.shape

(643638, 5)

#### Calculer le nombre de doublons dans le jeu de données.

In [30]:
print(df4.duplicated().sum())

0

#### Calculer la proportion de valeurs manquantes par colonne.

In [31]:
del df4["Unnamed: 4"]

In [32]:
round((df4.isnull().sum()/len(df4))* 100,2)

CountryCode    0.0
SeriesCode     0.0
Year           0.0
DESCRIPTION    0.0
dtype: float64

#### Calculer le nombre d'occurrences (Colonnes catégorielles)

In [33]:
for col in df4.select_dtypes(include="object").columns:
    print(f"__________{col}_________")
    print(df4[col].value_counts())
    print("\n")

__________CountryCode_________
CountryCode
LIC    7320
CYP    7183
LDC    6481
SSA    6389
SSF    6336
       ...
IMN      32
CUW      23
XKX      12
MNP       4
FRO       2
Name: count, Length: 239, dtype: int64


__________SeriesCode_________
SeriesCode
SH.DYN.MORT                 9226
SE.PRM.DURS                 8771
SE.PRM.AGES                 8771
SE.SEC.DURS                 8619
SE.SEC.AGES                 8581
                            ...
SABER.STD.ASS.GOAL2.LVL1       1
SABER.STD.ASS.GOAL2.LVL2       1
SABER.STD.ASS.GOAL2.LVL3       1
SABER.STD.ASS.GOAL3            1
SABER.ERL.CHLD.GOAL3           1
Name: count, Length: 1558, dtype: int64


__________Year_________
Year
YR2004    27128
YR2005    25992
YR2002    25687
YR2003    25683
YR2000    25093
YR2001    25047
YR2008    25018
YR1999    24938
YR2007    24263
YR2006    23394
YR2009    22965
YR2010    22598
YR2011    17760
YR1998    14916
YR2012    13890
YR2013    13405
YR1994    11448
YR2014    11378
YR1992    11309
YR1996    11197
YR1995    11194
YR1997    11167
YR1991    11129
YR1993    11093
YR1990    10616
YR1986     9743
YR1985     9653
YR1989     9517
YR1981     9465
YR1984     9386
YR1988     9382
YR1987     9357
YR1983     9227
YR1982     9014
YR1980     8950
YR1979     8742
YR1976     8729
YR1972     8661
YR1975     8627
YR1977     8593
YR1978     8585
YR1973     8571
YR1974     8512
YR1971     8507
YR2015     6348
YR1970     5374
YR2016      819
YR2017      558
YR2035      144
YR2050      144
YR2045      144
YR2040      144
YR2030      140
YR2025      140
YR2020      140
yr2012       14
Name: count, dtype: int64


__________DESCRIPTION_________
DESCRIPTION
Country Data                                      191188
UNESCO Institute for Statistics (UIS) estimate    171527
Estimated                                         117155
UIS Estimation                                     31395
Country estimation.                                26308
                                                   ...
Uncertainty bound is 73.8 - 86.4                       1
Uncertainty bound is 89 - 104.6                        1
Plausible bound is 14.2-19.8                           1
Plausible bound is 12.8-16.5                           1
Uncertainty bound is 127.1 - 148.2                     1
Name: count, Length: 9102, dtype: int64

### Jeu des données (5)

In [34]:
df5 = pd.read_csv("data/EdStatsSeries.csv")

In [35]:
df5.head()

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,...,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type,Unnamed: 20
0,BAR.NOED.1519.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15-19 with...,Percentage of female population age 15-19 with...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BAR.NOED.1519.ZS,Attainment,Barro-Lee: Percentage of population age 15-19 ...,Percentage of population age 15-19 with no edu...,Percentage of population age 15-19 with no edu...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BAR.NOED.15UP.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 15+ with n...,Percentage of female population age 15+ with n...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BAR.NOED.15UP.ZS,Attainment,Barro-Lee: Percentage of population age 15+ wi...,Percentage of population age 15+ with no educa...,Percentage of population age 15+ with no educa...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BAR.NOED.2024.FE.ZS,Attainment,Barro-Lee: Percentage of female population age...,Percentage of female population age 20-24 with...,Percentage of female population age 20-24 with...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Robert J. Barro and Jong-Wha Lee: http://www.b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3665 entries, 0 to 3664
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Series Code                          3665 non-null   object
 1   Topic                                3665 non-null   object
 2   Indicator Name                       3665 non-null   object
 3   Short definition                     2156 non-null   object
 4   Long definition                      3665 non-null   object
 5   Unit of measure                      0 non-null      float64
 6   Periodicity                          99 non-null     object
 7   Base Period                          314 non-null    object
 8   Other notes                          552 non-null    object
 9   Aggregation method                   47 non-null     object
 10  Limitations and exceptions           14 non-null     object
 11  Notes from original source           0 non-null      float64
 12  General comments                     14 non-null     object
 13  Source                               3665 non-null   object
 14  Statistical concept and methodology  23 non-null     object
 15  Development relevance                3 non-null      object
 16  Related source links                 215 non-null    object
 17  Other web links                      0 non-null      float64
 18  Related indicators                   0 non-null      float64
 19  License Type                         0 non-null      float64
 20  Unnamed: 20                          0 non-null      float64
dtypes: float64(6), object(15)
memory usage: 601.4+ KB

#### Calculer le nombre de lignes et de colonnes.

In [37]:
df5.shape

(3665, 21)

#### Calculer le nombre de doublons dans le jeu de données.

In [38]:
print(df5.duplicated().sum())

0

#### Calculer la proportion de valeurs manquantes par colonne.

In [39]:
del df5["Unnamed: 20"]

In [40]:
round((df5.isnull().sum()/len(df5))* 100,2)

Series Code                              0.00
Topic                                    0.00
Indicator Name                           0.00
Short definition                        41.17
Long definition                          0.00
Unit of measure                        100.00
Periodicity                             97.30
Base Period                             91.43
Other notes                             84.94
Aggregation method                      98.72
Limitations and exceptions              99.62
Notes from original source             100.00
General comments                        99.62
Source                                   0.00
Statistical concept and methodology     99.37
Development relevance                   99.92
Related source links                    94.13
Other web links                        100.00
Related indicators                     100.00
License Type                           100.00
dtype: float64

#### Calculer les statistiques descriptives

In [41]:
df5.describe(include="number")

,Unit of measure,Notes from original source,Other web links,Related indicators,License Type
count,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN

#### Calculer le nombre d'occurrences (Colonnes catégorielles)

In [42]:
for col in df5.select_dtypes(include="object").columns:
    print(f"__________{col}_________")
    print(df5[col].value_counts())
    print("\n")

__________Series Code_________
Series Code
XGDP.56.FSGOV.FDINSTADM.FFD    1
BAR.NOED.1519.FE.ZS            1
BAR.NOED.1519.ZS               1
BAR.NOED.15UP.FE.ZS            1
BAR.NOED.15UP.ZS               1
                              ..
BAR.NOED.5559.FE.ZS            1
BAR.NOED.5559.ZS               1
BAR.NOED.6064.FE.ZS            1
BAR.NOED.6064.ZS               1
BAR.NOED.6569.FE.ZS            1
Name: count, Length: 3665, dtype: int64


__________Topic_________
Topic
Learning Outcomes                                                                               1046
Attainment                                                                                       733
Education Equality                                                                               426
Secondary                                                                                        256
Primary                                                                                          248
Population                                                                                       213
Tertiary                                                                                         158
Teachers                                                                                         137
Expenditures                                                                                      93
Engaging the Private Sector (SABER)                                                               51
Literacy                                                                                          32
Teachers (SABER)                                                                                  29
School Autonomy and Accountability (SABER)                                                        29
Early Childhood Education                                                                         24
Education Management Information Systems (SABER)                                                  23
Post-Secondary/Non-Tertiary                                                                       19
School Finance (SABER)                                                                            18
Tertiary Education (SABER)                                                                        17
Student Assessment (SABER)                                                                        15
Pre-Primary                                                                                       14
Health: Population: Structure                                                                     13
Early Child Development (SABER)                                                                   12
Workforce Development (SABER)                                                                     12
Social Protection & Labor: Labor force structure                                                  11
School Health and School Feeding (SABER)                                                           9
Economic Policy & Debt: Purchasing power parity                                                    6
Economic Policy & Debt: National accounts: US$ at current prices: Aggregate indicators             3
Laber                                                                                              3
Social Protection & Labor: Unemployment                                                            3
Infrastructure: Communications                                                                     2
EMIS                                                                                               2
Economic Policy & Debt: National accounts: US$ at constant 2010 prices: Aggregate indicators       2
Background                                                                                         2
Economic Policy & Debt: National accounts: Atlas GNI & GNI per capita                              1
Health: Risk factors                                                                               1
Health: Mortality                                                                                  1
Health: Population: Dynamics                                                                       1
Name: count, dtype: int64


__________Indicator Name_________
Indicator Name
Government expenditure in tertiary institutions as % of GDP (%)           1
Barro-Lee: Percentage of female population age 15-19 with no education    1
Barro-Lee: Percentage of population age 15-19 with no education           1
Barro-Lee: Percentage of female population age 15+ with no education      1
Barro-Lee: Percentage of population age 15+ with no education             1
                                                                         ..
Barro-Lee: Percentage of female population age 55-59 with no education    1
Barro-Lee: Percentage of population age 55-59 with no education           1
Barro-Lee: Percentage of female population age 60-64 with no education    1
Barro-Lee: Percentage of population age 60-64 with no education           1
Barro-Lee: Percentage of female population age 65-69 with no education    1
Name: count, Length: 3665, dtype: int64


__________Short definition_________
Short definition
Data Interpretation: 1=Latent; 2=Emerging; 3=Established; 4=Advanced. For additional information, visit the SABER: (website: http://saber.worldbank.org/index.cfm                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  215
Share of students who scored 80 percent or higher on the reading comprehension assessment. The reading comprehension subtask follows the oral reading fluency subtask; students are required to respond to literal and inferential questions about the oral reading fluency subtask text they have just read. The questions are read aloud to the student by the assessor. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                                                                             51
Share of students who scored zero percent on the reading comprehension assessment. The reading comprehension subtask follows the oral reading fluency subtask; students are required to respond to literal and inferential questions about the oral reading fluency subtask text they have just read. The questions are read aloud to the student by the assessor. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                                                                                                                                                                                           51
Average total number of invented/nonsense words correctly read per minute. The indicator measures students' ability to fluently decipher/decode randomly-presented “words” that follow linguistic rules but do not actually exist in the stated language. Skill in reading nonwords can be a purer measure of decoding than using real words because children cannot recognize the words by sight. Decoding is considered a self-teaching skill that enables children to read new and unfamiliar words independently. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                  51
Percentage of students who were unable to read a single word of text on the oral reading fluency subtask. The oral reading fluency/paragraph reading subtask examines students' ability to read a narrative or informational text with accuracy, with little effort, and at a sufficient rate. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               51
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ...
The percentage of male population (age 25 and over) with at least completed upper secondary education (ISCED 3 or higher). This indicator is calculated by dividing the number of males aged 25 years and above who completed upper secondary education by the total male population of the same age group and multiplying the result by 100. The UNESCO Institute for Statistics (UIS) educational attainment dataset shows the educational composition of the population aged 25 years and above and hence the stock and quality of human capital within a country. The dataset also reflects the structure and performance of the education system and its accumulated impact on human capital formation. For more information, visit the UNESCO Institute for Statistics website: http://www.uis.unesco.org/                                                                                     1
The percentage of population (age 25 and over) with completed post-secondary education (ISCED 4) as the highest level of educational attainment. This indicator is calculated by dividing the number of persons aged 25 years and above who completed post-secondary education as the highest level of educational attainment by the total population of the same age group and multiplying the result by 100. The UNESCO Institute for Statistics (UIS) educational attainment dataset shows the educational composition of the population aged 25 years and above and hence the stock and quality of human capital within a country. The dataset also reflects the structure and performance of the education system and its accumulated impact on human capital formation. For more information, visit the UNESCO Institute for Statistics website: http://www.uis.unesco.org/                    1
The percentage of female population (age 25 and over) with completed post-secondary education (ISCED 4) as the highest level of educational attainment. This indicator is calculated by dividing the number of females aged 25 years and above who completed post-secondary education as the highest level of educational attainment by the total female population of the same age group and multiplying the result by 100. The UNESCO Institute for Statistics (UIS) educational attainment dataset shows the educational composition of the population aged 25 years and above and hence the stock and quality of human capital within a country. The dataset also reflects the structure and performance of the education system and its accumulated impact on human capital formation. For more information, visit the UNESCO Institute for Statistics website: http://www.uis.unesco.org/      1
The percentage of male population (age 25 and over) with completed post-secondary education (ISCED 4) as the highest level of educational attainment. This indicator is calculated by dividing the number of males aged 25 years and above who completed post-secondary education as the highest level of educational attainment by the total male population of the same age group and multiplying the result by 100. The UNESCO Institute for Statistics (UIS) educational attainment dataset shows the educational composition of the population aged 25 years and above and hence the stock and quality of human capital within a country. The dataset also reflects the structure and performance of the education system and its accumulated impact on human capital formation. For more information, visit the UNESCO Institute for Statistics website: http://www.uis.unesco.org/            1
Percentage of female population age 15+ with no education                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
Name: count, Length: 1169, dtype: int64


__________Long definition_________
Long definition
Data Interpretation: 1=Latent; 2=Emerging; 3=Established; 4=Advanced. For additional information, visit the SABER: (website: http://saber.worldbank.org/index.cfm                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     215
Share of students who scored zero percent on the reading comprehension assessment. The reading comprehension subtask follows the oral reading fluency subtask; students are required to respond to literal and inferential questions about the oral reading fluency subtask text they have just read. The questions are read aloud to the student by the assessor. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                              51
Percentage of students who were unable to read a single word of text on the oral reading fluency subtask. The oral reading fluency/paragraph reading subtask examines students' ability to read a narrative or informational text with accuracy, with little effort, and at a sufficient rate. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                                                                                                                                                                                                  51
Share of students who scored 80 percent or higher on the reading comprehension assessment. The reading comprehension subtask follows the oral reading fluency subtask; students are required to respond to literal and inferential questions about the oral reading fluency subtask text they have just read. The questions are read aloud to the student by the assessor. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.                                                                                                                                                51
Average total number of invented/nonsense words correctly read per minute. The indicator measures students' ability to fluently decipher/decode randomly-presented “words” that follow linguistic rules but do not actually exist in the stated language. Skill in reading nonwords can be a purer measure of decoding than using real words because children cannot recognize the words by sight. Decoding is considered a self-teaching skill that enables children to read new and unfamiliar words independently. Users are discouraged from using these data to make direct comparisons across countries or languages. Consult the EdData website and the specific country report for more information: www.eddataglobal.org.     51
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ...
Population in thousands, age 25+, female is the female population over age 25 in thousands estimated by Barro-Lee.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1

## Etape 2 : Réaliser le premier nettoyage

In [43]:
data = pd.read_csv("data/EdStatsCountry.csv").dropna(how="all")
data.head()
del data["Unnamed: 31"]

In [44]:
data.duplicated().sum()

np.int64(0)

In [45]:
# la creation d'une liste de faux pays

fake_df = data[data["Region"].isnull()]

faux_pays = []
for val in fake_df["Short Name"]:
    faux_pays.append(val)
print(faux_pays)

['Arab World', 'East Asia & Pacific (developing only)', 'East Asia & Pacific (all income levels)', 'Europe & Central Asia (developing only)', 'Europe & Central Asia (all income levels)', 'Euro area', 'European Union', 'Gibraltar', 'High income', 'Heavily indebted poor countries (HIPC)', 'Latin America & Caribbean (developing only)', 'Latin America & Caribbean (all income levels)', 'Least developed countries: UN classification', 'Low income', 'Lower middle income', 'Low & middle income', 'Middle East & North Africa (all income levels)', 'Middle income', 'Middle East & North Africa (developing only)', 'North America', 'Nauru', 'OECD members', 'South Asia', 'Sub-Saharan Africa (developing only)', 'Sub-Saharan Africa (all income levels)', 'Upper middle income', 'World']

In [46]:
# filteration des faux pays

filtered_df = data[~data["Short Name"].isin(faux_pays)]

In [47]:
# Fusionner le dataframe nettoyé avec df2 

df2_clean = df2.merge(filtered_df[["Short Name"]], on = "Short Name",how = "inner")

In [48]:
# Fusionner le dataframe nettoyé avec df3

df3_clean = df3.merge(filtered_df[["Short Name"]], how = "inner", left_on = "Country Name", right_on = "Short Name")

In [49]:
# Fusionner le dataframe nettoyé avec df4

df4_clean = df4.merge(filtered_df[["Country Code"]], how="inner", left_on = "CountryCode", right_on = "Country Code").drop("CountryCode", axis = "columns")

In [50]:
# Fusionner le dataframe nettoyé avec df4
df1_clean = df1.merge(filtered_df[["Country Code"]], how="inner", left_on = "CountryCode", right_on = "Country Code").drop("CountryCode", axis = "columns")